#!/usr/bin/env bash
# Genera bibliaapp-desktop-0.3.0-1-x86_64.pkg.tar.zst para pacman -U
# Requiere: cd desktop && npm run icons && npm run build:arch

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUTDIR="$(cd "$(dirname "$0")" && pwd)"
PKGDIR=$(mktemp -d)
BUILD_DATE=$(date +%s)
PKGVER=0.3.0
PKGREL=1

BIN="$ROOT/src-tauri/target/release/bibliaapp-desktop"
ICON_SRC="$ROOT/app-icon.png"
if [[ ! -f "$ICON_SRC" ]]; then
  ICON_SRC="$ROOT/src-tauri/icons/128x128.png"
fi

if [[ ! -f "$BIN" ]]; then
  echo "Falta el binario. Ejecuta: cd $ROOT && npm run build:arch" >&2
  exit 1
fi

mkdir -p "$PKGDIR/usr/bin" "$PKGDIR/usr/share/applications"

install -Dm755 "$BIN" "$PKGDIR/usr/bin/bibliaapp-desktop"

cat > "$PKGDIR/usr/share/applications/bibliaapp-desktop.desktop" <<'EOF'
[Desktop Entry]
Name=BibliaAPP
Comment=Lectura bíblica y comunidad
Exec=bibliaapp-desktop
Icon=bibliaapp
Terminal=false
Type=Application
Categories=Education;Spirituality;
StartupWMClass=bibliaapp
EOF

for size in 16 32 48 128 256; do
  icon="$ROOT/src-tauri/icons/${size}x${size}.png"
  if [[ -f "$icon" ]]; then
    install -Dm644 "$icon" "$PKGDIR/usr/share/icons/hicolor/${size}x${size}/apps/bibliaapp.png"
  else
    install -Dm644 "$ICON_SRC" "$PKGDIR/usr/share/icons/hicolor/${size}x${size}/apps/bibliaapp.png"
  fi
done

SIZE=$(du -sb "$PKGDIR/usr" | cut -f1)

cat > "$PKGDIR/.PKGINFO" <<EOF
# Generated by build-pacman-pkg.sh
pkgname = bibliaapp-desktop
pkgbase = bibliaapp-desktop
pkgver = ${PKGVER}-${PKGREL}
pkgdesc = Lectura bíblica, comunidad y grupos — cliente de escritorio BibliaAPP
url = https://biblia2.dvguzman.com
builddate = $BUILD_DATE
packager = BibliaAPP
size = $SIZE
arch = x86_64
license = custom
depend = webkit2gtk-4.1
depend = gtk3
depend = glib2
depend = libsoup3
depend = libappindicator-gtk3
depend = librsvg
depend = hicolor-icon-theme
EOF

PKGFILE="$OUTDIR/bibliaapp-desktop-${PKGVER}-${PKGREL}-x86_64.pkg.tar.zst"
cd "$PKGDIR"
fakeroot tar --zstd -cf "$PKGFILE" --owner=root --group=root --sort=name .PKGINFO usr
rm -rf "$PKGDIR"

echo "Paquete creado: $PKGFILE"
echo "Instalar: sudo pacman -U $PKGFILE"
echo "Iconos: gtk-update-icon-cache /usr/share/icons/hicolor  (pacman lo hace al instalar)"
